name: ${COMPOSE_PROJECT_NAME}  #nome prj! (se non lo specifici qua allora si setta come nome folder che contiene questo docker-compose file) quindi ora e.g.i nomi dei containers saranno <project_name>-<service_name>-<index>

services:

  ragsystem-frontend:
    build:
      context: .
      dockerfile: RagSystemFrontend.UI/Dockerfile
    #image: ragsystem-frontend:latest   #x dare nome custom alla build che crei
    restart: unless-stopped
    ports:
      - "8091:8080"   #host 8090  ->  container 8080 (dove ascolta Kestrel)(anche chainlit su backend usa quella porta docker (8080), ok nessun problema x docker intanto sono distinte/docker capisce che sono differenti). sul browser http://192.168.113.52:8090
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}   #con 'Development' renderizzi anche logs di stack tracing
      - ASPNETCORE_HTTP_PORTS=8080     #porta interna del container, okey
      - BackendApi__BaseUrl=http://192.168.113.40/:8001    #nome del service del backend che utilizzi

    networks:
      - rag-network

networks:
  rag-network:
    name: ${DOCKER_NETWORK}   #deve essere esattamente identica a quella del backend, e.g.'rag-dev-network', il ragfrontend deve entrare nella rete del backend! in totale 1 sola rete!
    external: true 


